Reshaping Arrays:

In [ ]:
import numpy as np

arr = np.arange(12)
arr_rashaped = arr.reshape((3, 4))
print(arr_rashaped)

🔹 2.2 Array Indexing and Slicing

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[0,1]) # Access element at first row, second column
print(arr[:, 1]) # Access all rows in second column
print(arr[1, :]) # Access all columns in second row


2
[2 5 8]
[4 5 6]


Hands-On Challenge

Task:

Create a 1D array of numbers from 10 to 49 using np.arange.

Reshape it into a 4×10 array.

Print:

shape

number of dimensions

total size

Extract the second column of the reshaped array.

In [10]:
arr = np.arange(10,50)
print(arr)
arr_reshaped = arr.reshape((4,10))
print(arr_reshaped)
print(arr_reshaped.shape)
print(arr_reshaped.ndim)
print(arr_reshaped.size)
print(arr_reshaped[1,:])


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
(4, 10)
2
40
[20 21 22 23 24 25 26 27 28 29]
